
/*
 * FCLKS are in MHz
 */
typedef enum {
    TWOptFIVE = 0,			FIVE = 1,				SEVENptFIVE = 2,
    TEN = 3,				TWELVEptFIVE = 4,		FIFTEEN = 5,
    SEVENTEENptFIVE = 6,	TWENTY = 7,				TWENTYTWOptFIVE = 8,
    TWENTYFIVE = 9,			TWENTYSEVENptFIVE = 10,	THIRTY = 11,
    THIRTYTWOptFIVE = 12,	THIRTYFIVE = 13,		THIRTYSEVENptFIVE = 14,
    FOURTY = 15,			FOURTYTWOptFIVE = 16,	FOURTYFIVE = 17,
    FIFTY = 18,			    FIFTYFIVE = 19,		    SIXTY = 20,
    SIXTYFIVE = 21,		    SEVENTY = 22,		    SEVENTYFIVE = 23,
    EIGHTY = 24,			EIGHTYFIVE = 25,		NINETY = 26,
    ONEHUNDRED = 27,		ONEHUNDREDTEN = 28,	    ONEHUNDREDTWENTY = 29,
    ONEHUNDREDTHIRTY = 30,  ONEHUNDREDFOURTY = 31,	ONEHUNDREDFIFTY = 32,
    ONEHUNDREDSIXTY = 33,   ONEHUNDREDSEVENTY = 34,	ONEHUNDREDEIGHTY = 35
} FCLKS;

void SysClkInit(FCLKS);
void TimerInit(float32);
float32 getfclk(void);
